version: 2 # use CircleCI 2.0
jobs:
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.11

    # directory where steps are run. Path must conform to the Go Workspace requirements
    working_directory: /go/src/github.com/surmus/injection

    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run: mkdir -p $TEST_RESULTS # create the test results directory

      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - v1-pkg-cache

      # Normally, this step would be in a custom primary image;
      # we've added it here for the sake of explanation.
      - run: go get github.com/jstemmer/go-junit-report

      - run: make install
      - run: make vet
      - run: fmt-check

      - run:
          name: Run unit tests
          # store the results of our tests in the $TEST_RESULTS directory
          command:
            trap "go-junit-report <tmp.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test

      - save_cache: # store cache in the /go/pkg directory
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
      # Send coverage test reports to codecov
      - run: bash <(curl -s https://codecov.io/bash)
      - store_test_results: # upload test results for display in Test Summary
          path: /tmp/test-results